//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Person> PersonSet { get; set; }
        public virtual DbSet<Module> ModuleSet { get; set; }
        public virtual DbSet<Form> FormSet { get; set; }
        public virtual DbSet<Rol> RolSet { get; set; }
        public virtual DbSet<Permisos> PermisosSet { get; set; }
        public virtual DbSet<moduleForm> moduleFormSet { get; set; }
        public virtual DbSet<Permision> PermisionSet { get; set; }
        public virtual DbSet<UserRol> UserRolSet { get; set; }
        public virtual DbSet<RolFormPermission> RolFormPermissionSet { get; set; }
    }
}
